const predefinedCells = {
    "B1": {"letter": "අ", "value": 1},
  "C1": {"letter": "ග", "value": 8},
  "C2": {"letter": "ත", "value": 10},
  "D2": {"letter": "ර", "value": 6},
  "E2": {"letter": "ම", "value": 2},
  "E1": {"letter": "ස්", "value": 3},
  "D3": {"letter": "ති", "value": 4},
  "E3": {"letter": "ර", "value": 6},
  "E4": {"letter": "ණ", "value": 5},
  "F1": {"letter": "තූ", "value": 6},
  "G1": {"letter": "ති", "value": 4},
  "G2": {"letter": "ර", "value": 6},
  "F3": {"letter": "ස", "value": 8},
  "F4": {"letter": "ය", "value": 9},
  "G4": {"letter": "ට", "value": 9},
  "F5": {"letter": "න", "value": 10},
  "G5": {"letter": "යි", "value": 1},
  "A2": {"letter": "සු", "value": 2},
  "A3": {"letter": "ක", "value": 6},
  "B3": {"letter": "ප", "value": 3},
  "B4": {"letter": "හ", "value": 4},
  "B5": {"letter": "න", "value": 10},
  "A5": {"letter": "ත", "value": 10},
  "C5": {"letter": "ව", "value": 5},
  "D5": {"letter": "ල", "value": 6},
  "A6": {"letter": "ම", "value": 2},
  "A7": {"letter": "ර", "value": 6},
  "K1": {"letter": "උ", "value": 3},
  "K2": {"letter": "ඩ", "value": 0}, // Assuming a value since it's not listed in letterValues
  "K3": {"letter": "ර", "value": 6},
  "K4": {"letter": "ට", "value": 9},
  "J3": {"letter": "ක", "value": 6},
  "J4": {"letter": "ම", "value": 2},
  "J5": {"letter": "ල", "value": 6},
  "L2": {"letter": "ක", "value": 6},
  "L3": {"letter": "ට", "value": 9},
  "I4": {"letter": "සු", "value": 2},
  "M1": {"letter": "ප", "value": 3},
  "M2": {"letter": "ය", "value": 9},
  "E12": {"letter": "ස්", "value": 3},
  "F11": {"letter": "වි", "value": 8},
  "F12": {"letter": "වා", "value": 9},
  "F13": {"letter": "ද", "value": 10},
  "G11": {"letter": "ව", "value": 5},
  "G12": {"letter": "යු", "value": 2},
  "H11": {"letter": "ර", "value": 6},
  "I11": {"letter": "ණ", "value": 5},
  "J11": {"letter": "ය", "value": 9},
  "L11": {"letter": "ර", "value": 6},
  "M11": {"letter": "න", "value": 10},
  "N11": {"letter": "ව", "value": 5},
  "O11": {"letter": "රා", "value": 7},
  "M12": {"letter": "ය", "value": 9},
  "N12": {"letter": "ර", "value": 6},
  "N13": {"letter": "ය", "value": 9},
  "O13": {"letter": "ස", "value": 8},
  "O14": {"letter": "ය", "value": 9}
  };
  
  export { predefinedCells };
  